
protocol: ???

input:
  duration: 2.0
  sample_rate: 16000
  num_channels: 1

training:
  batch_size: 32
  num_workers: 4

task:
  duration: ${input.duration}
  batch_size: ${training.batch_size}
  num_workers: ${training.num_workers}

model:
  sample_rate: ${input.sample_rate}
  num_channels: ${input.num_channels}

defaults:
  - task: vad
  - model: debug
