# @package _group_
_target_: pyannote.audio.tasks.OverlappedSpeechDetection
duration: 3.0
augmentation_probability: 0.5
snr_min: 0.0
snr_max: 10.0
domain: null
batch_size: 32
num_workers: null
pin_memory: False
